### PR TITLE
First cut at resource_update. 

### PR DESCRIPTION
**Pull request by florianm**
Addressing #11 

The tests depend on an existing CKAN demo url/api key/resource id in the global variables.

The code is based upon `ds_dataset_create`, which conveniently did all the homework for `resource_update`.

I'd value your opinion on:

* should we ckan_POST to utilise the globally set api key, or keep `ds_dataset_create`'s httr::POST?
* what's the preferred way of handling CKAN url and api key? My implementation looks clunky, but at least it defaults to global variables while allowing the user to override both on a case-by-case basis.
* tests depend on a live CKAN instance, to which the respective tester has an authorised API key, and the id of an existing resource. Documented in inline comments of `tests/testthat/test-resource_update.R`. Would it be cleaner to do that globally for all POSTing function tests and document in the vignette?

### CODE REVIEW

**Comment by sckott** [comment]
thanks @florianm 

> should we ckan_POST to utilise the globally set api key, or keep ds_dataset_create's httr::POST?

the datastore functions were added relatively recently, and I didn't get around to unifying with `ckan_POST` yet - you can use `ckan_POST` instead

> what's the preferred way of handling CKAN url and api key?

I think what you have is good. I think we should have a `key` parameter in all functions that need a key so there are many paths to using a key (Setting via options or passing in as a parameter)

> Would it be cleaner to do that globally for all POSTing function tests and document in the vignette?

To do what globally?

**Comment by florianm** [comment]
re `ckan_POST` - I can't implement this with less code than using `httr::POST` and without doubling up on the API key handling logic in `ckan_POST`. I'll clean up my API key default (l.43), but my "b.y.o. API key or use the key from ckanr_options" logic parallels `ckan_POST`'s "use ckanr_options" approach.
I assume every create/update/delete function will have to handle api key logic similar to `resource_update` - would it be feasible to give `ckan_POST` an explicit `key=NULL` parameter, and use that over `api_key()`?

re url and key in parameters - I agree we'll need both the url and the key as parameters (with sensible defaults) for these two use cases:

* Many `resource_update`s to the same CKAN with the same API key: `set_ckan_url` and `set_api_key` once, then fire off many `resource_update`s which default to my set url and key.
* Many `resource_update`s to different urls or with different keys: url and key should be function parameters.

re testing: `test-resource_update.R` depends on a live CKAN instance and the respective tester having a privileged API key to at least one resource id. All three of these parameters will vary vigorously between each tester, so the best I could come up with was adding them to `ckanr_options`. Again I suspect that every creating/updating/deleting test will need these settings. Is this approach valid or is there a better way to handle the dependency on a live CKAN instance?

**Comment by sckott** [comment]
it looks like #31 also replaces this PR?  

If so, i'll continue discussion there and close this

**Comment by florianm** [comment]
If #31 (which contains all commits of this PR) makes sense to you, feel free to close #29. I wanted to keep my musings about test suites out of this relatively clean PR.

**Comment by sckott** [comment]
> would it be feasible to give `ckan_POST` an explicit `key=NULL` parameter, and use that over `api_key()`

I think we can give `ckan_POST` a `key` parameter, but if that's NULL, then we should look in options to see if user set it there.  I think this will support your two use cases listed above. 

For testing, we can use environment variables, which can be set on our own machines, and on Travis-CI . E.g., in this test https://github.com/ropensci/ckanr/blob/master/tests/testthat/test-ds_create_dataset.R#L4 I read in an envir. variable, so it's not exposed on github, and it's also on Travis, so test should work there too.

**Pull request closed without merging**
