### PR TITLE
added parameter include_datasets=FALSE to tag_show to match CKAN API

### PR DESCRIPTION
**Pull request by florianm**
Addressing #41 tests pass again with Travis's test server settings (data-demo.dpaw.wa.gov.au).

### CODE REVIEW

**Comment by florianm** [comment]
@sckott Does Travis still use the set settings on data-demo? Looks like there's something wrong with the test config rather than the code. Just a guess though.

**Comment by sckott** [comment]
i am quite sure that we are using the newer test env vars

I'll merge this, and see if it fixes that test, and if not, try to fix it then

**Comment by florianm** [comment]
Blue moon bug again. The test server is an aws ec2 t2.medium running out of Sydney fwiw. Well at least tests are passing now although I can't explain why they failed above.

**Comment by sckott** [comment]
i don't know either, hopefully we're good to go now

**Pull request merged**
