### PR TITLE
Add optional format argument to ckan_fetch()

### LINKED ISSUE #116: ckan_fetch() fails when resource URL doesn't contain file format
In updating the examples for `ckan_fetch()`, I ran into a lot of cases where the file format isn't actually in the resource URL and so `ckan_fetch()` fails (somewhat uninformatively):

``` r
library(ckanr)
#> Loading required package: DBI

ckanr_setup("https://data.europa.eu/euodp/data/")
res <- resource_show(id = "f2cfb3f8-44f6-4027-952f-a1d759484501", as = "table")

res$url
#> [1] "http://www.emcdda.europa.eu/data/stats2018/dlo"
res$format
#> [1] "HTML"

ckan_fetch(res$url, format = "")
#> Error in if (file_fmt(x) == "xls") {: argument is of length zero
```

<sup>Created on 2019-06-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

From what I've seen, the file format is often (always? I'm not a CKAN expert) available in that `res` object. Would you be interested in a PR for an optional `format` argument to `ckan_fetch()`? It could either be taken straight from the `res` object or just user-specified.

### PR DESCRIPTION
**Pull request by sharlagelfand**
Adds an additional (optional) `format` parameter to `ckan_fetch()` so that downloading can succeed even if the resource URL doesn't have the format in its extension; closes #116. I also started a test file for `ckan_fetch()`, starting with ensuring that the error works as expected.

Some examples:
``` r
library(ckanr)
#> Loading required package: DBI

ckanr_setup("https://data.europa.eu/euodp/data/")
res <- resource_show(id = "f2cfb3f8-44f6-4027-952f-a1d759484501", as = "table")
ckan_fetch(res$url)
#> Error in ckan_fetch(res$url): File format is not available from URL; please specify via `format` argument.
ckan_fetch(res$url, format = res$format)
#> {xml_document}
#> <html lang="en" dir="ltr" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:dc="http://purl.org/dc/terms/" xmlns:foaf="http://xmlns.com/foaf/0.1/" xmlns:og="http://ogp.me/ns#" xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#" xmlns:sioc="http://rdfs.org/sioc/ns#" xmlns:sioct="http://rdfs.org/sioc/types#" xmlns:skos="http://www.w3.org/2004/02/skos/core#" xmlns:xsd="http://www.w3.org/2001/XMLSchema#">
#> [1] <head profile="http://www.w3.org/1999/xhtml/vocab">\n<meta charset=" ...
#> [2] <body class="html not-front not-logged-in one-sidebar sidebar-first  ...

ckanr_setup("https://ckan0.cf.opendata.inter.sandbox-toronto.ca")
res <- resource_show(id = "75c69a49-8573-4dda-b41a-d312a33b2e05", as = "table")
head(ckan_fetch(res$url))
#> Error in ckan_fetch(res$url): File format is not available from URL; please specify via `format` argument.
head(ckan_fetch(res$url, format = res$format))
#>      X_id estStatusDesc enfrID inspID infrTypeCD postal rowNo
#> 1 2214143          Pass     NA  72246      10005    M1G     1
#> 2 2214144          Pass     NA  72246      10011    M1G     2
#> 3 2214145          Pass     NA  72246      10015    M1G     3
#> 4 2214146          Pass     NA  72247      10012    M1G     4
#> 5 2214147          Pass     NA  72247      10015    M1G     5
#> 6 2214148          Pass     NA  72248      10005    M1G     6
#>                  addr          estName       infrAction       lon servID
#> 1 3770 LAWRENCE AVE E PINK NAILS & SPA Notice to Comply -79.21424 556681
#> 2 3770 LAWRENCE AVE E PINK NAILS & SPA Notice to Comply -79.21424 556681
#> 3 3770 LAWRENCE AVE E PINK NAILS & SPA Notice to Comply -79.21424 556681
#> 4 3770 LAWRENCE AVE E PINK NAILS & SPA Notice to Comply -79.21424 556682
#> 5 3770 LAWRENCE AVE E PINK NAILS & SPA Notice to Comply -79.21424 556682
#> 6 3770 LAWRENCE AVE E PINK NAILS & SPA Notice to Comply -79.21424 556681
#>   enfrOutcome unit
#> 1                 
#> 2                 
#> 3                 
#> 4                 
#> 5                 
#> 6                 
#>                                                                      infrTypeDesc
#> 1                                        Single-use items used on one client only
#> 2                  Semi-critical items maintained in a sanitary manner before use
#> 3                         Work surfaces cleaned then disinfected with a LLD daily
#> 4 Semi-critical items cleaned then disinfected with an ILD or HLD between clients
#> 5                         Work surfaces cleaned then disinfected with a LLD daily
#> 6                                        Single-use items used on one client only
#>   enfrAmountFined inspStatusDesc enfrOutcomeDate     lat servTypeCD
#> 1              NA    Conditional                 43.7625       7017
#> 2              NA    Conditional                 43.7625       7017
#> 3              NA    Conditional                 43.7625       7017
#> 4              NA    Conditional                 43.7625       7018
#> 5              NA    Conditional                 43.7625       7018
#> 6              NA    Conditional                 43.7625       7017
#>              inspDate infrID  addrID   estID servTypeDesc estStatusCD
#> 1 2016-11-09T00:00:00   8460 2907806 3644116        Nails        PASS
#> 2 2016-11-09T00:00:00   8461 2907806 3644116        Nails        PASS
#> 3 2016-11-09T00:00:00   8462 2907806 3644116        Nails        PASS
#> 4 2016-11-09T00:00:00   8463 2907806 3644116   Aesthetics        PASS
#> 5 2016-11-09T00:00:00   8464 2907806 3644116   Aesthetics        PASS
#> 6 2016-11-15T00:00:00   8465 2907806 3644116        Nails        PASS
```

<sup>Created on 2019-06-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

### CODE REVIEW

**Comment by sckott** [comment]
thanks! can you split into two separate PRs though - one with adding the test and one with the change to ckan_fetch

**Comment by sharlagelfand** [comment]
Yup! Removed the test from this PR, it's in #118 now. Thanks!

**Comment by sckott** [comment]
thanks! looks good

**Comment by hannaboe** [comment]
Perfect, thank you!

**Pull request merged**
