### PR TITLE
correct error handler

### PR DESCRIPTION
**Pull request by wush978**
resolve ropensci/ckanr#19

### CODE REVIEW

**Comment by wush978** [comment]
I'll correct the failed test in a couple days.

**Comment by sckott** [comment]
Testing this locally, the error message is too messy now.  I think it's easy enough to pull out just the error message. e.g. using your changes in this PR I get

```r
changes(offset = "adf")
```

```r
Error: 409 - client error: (409) Conflict

{"help": "Return the activity stream of all recently added or changed packages.\n\n    :param offset: where to start getting activity items from\n        (optional, default: 0)\n    :type offset: int\n    :param limit: the maximum number of activities to return\n        (optional, default: 31, the default value is configurable via the\n        ckan.activity_list_limit setting)\n    :type limit: int\n\n    :rtype: list of dictionaries\n\n    ", "success": false, "error": {"__type": "Validation Error", "offset": ["Invalid integer"]}} 
```

we could pull out just the error message e.g., like `jsonlite::fromJSON(errmssg)$error`  - and if it's not always there, just use a `tryCatch`

**Comment by wush978** [comment]
Good idea! 

By the way, today they tell me that the site I tried does not allow ckan API (but they do build the site upon ckan), so the response is not json formatted but html.

**Comment by wush978** [comment]
Because I don't want to break the unit test, so this version will try the original `err_handler` and switch to a more verbose version if the original `err_handler` does not work.

And I do not add the unit test for the updated version, so please merge the PR later.

**Comment by sckott** [comment]
@wush978 so you're sending another patch soon?

**Comment by wush978** [comment]
@sckott , the unit test is added in 5fb02e6. So this PR is ready to be merged.

**Comment by sckott** [comment]
@wush978 okay, thanks

**Pull request merged**
