### PR TITLE
Rework tests to use demo.ckan.org

### PR DESCRIPTION
**Pull request by florianm**
### Issue
TravisCI fails [build 162](https://travis-ci.org/ropensci/ckanr/builds/220387385) with:

```
checking for code/documentation mismatches ... WARNING
Codoc mismatches from documentation object 'ckan_info':
ckan_version
  Code: function(url, ...)
  Docs: function(url)
  Argument names in code not in docs:
    ...
```

### Actions taken

```{r}
devtools::document(roclets=c('rd', 'collate', 'namespace'))
# all man/*.rd files rebuilt

devtools::check(cran = TRUE, force_suggests = TRUE, check_version = TRUE)
R CMD check results
0 errors | 0 warnings | 1 note 
checking CRAN incoming feasibility ... NOTE
Maintainer: ‘Scott Chamberlain <myrmecocystus@gmail.com>’

Version contains large components (0.1.2.9840)

License components with restrictions and base license permitting such:
  MIT + file LICENSE
File 'LICENSE':
  YEAR: 2016
  COPYRIGHT HOLDER: Scott Chamberlain
```

Let's see whether Travis checks pass with this.

### CODE REVIEW

**Comment by florianm** [comment]
covr still fails. Running locally:

```
> covr::codecov()
Error: Failure in `/tmp/Rtmpmnr00z/R_LIBS80dd1726c1/ckanr/ckanr-tests/test-all.Rout.fail`
> library("testthat")
> library("ckanr")
Loading required package: DBI
> 
> # Test CKAN fallback
> if(is.null(get_test_url())) ckanr_setup(test_url="http://demo.ckan.org")
> 
> test_check("ckanr")
1. Error: changes gives back expected class types (@test-changes.R#7) ----------
Couldn't resolve host name
1: ckanr::changes(url = u) at testthat/test-changes.R:7
2: ckan_GET(url, "recently_changed_packages_activity_list", args, ...)
3: ckan_VERB("GET", url, method, body = NULL, key, query = query, ...)
4: VERB(file.path(url, ck(), method), ctj(), ...)
5: request_perform(req, hu$handle$handle)
6: request_fetch(req$output, req$url, handle)
7: request_fetch.write_memory(req$output, req$url, handle)
8: curl::curl_fetch_memory(url, handle = handle)

2. Error: changes works giving back json output (@test-changes.R#17) -----------
Couldn't resolve host name
1: ckanr::changes(url = u, as = "json") at testthat
```

**Comment by sckott** [comment]
http://catalogue.alpha.data.wa.gov.au/ appears to be down

**Comment by florianm** [comment]
My bad, they took catalogue.alpha offline a while back. Where is it still linked in the ckanr code? Can't find it.

**Comment by sckott** [comment]
it's set in the env vars on travis, and had been using locally as well, but hadn't tested it in a while

**Comment by florianm** [comment]
Ah, of course, that makes sense. catalogue.alpha is down, data-demo.dpaw.wa.gov.au is currently down as it's run by datacats (a Docker orchestrator) which is impossible to orchestrate itself - requiring manual restarts whenever it's having a hiccup.

Is there a good testing instance? I'll test demo.ckan.org with my account there in the mean time.

**Comment by sckott** [comment]
> Is there a good testing instance?

I'd like to maintain one myself, but haven't had success getting one up :( 

i guess demo for now yeah

**Comment by florianm** [comment]
To run tests on demo.ckan.org, register on demo.ckan.org, get the API key and run

```{r}
Sys.setenv(TEST_API_KEY = "my-demo-ckan-org-api-key")
prepare_test_ckan()
```

or 

```{r}
prepare_test_ckan(test_key="my-demo-ckan-org-api-key")
```

* `organization_list` is slow on instances with lots of orgs, like demo.ckan.org - introduced a `limit` parameter to `organization_list` similar to `group_list` - this means the default behaviour changes from returning all to returning 31 orgs - is this ok?
* `resource_update` is broken (see [95c11aee](https://github.com/ropensci/ckanr/pull/89/commits/95c11aee21d8344ebe3902755ce5663cba38d501))
* test-tag_show is broken ([patched](https://github.com/ropensci/ckanr/pull/89/commits/a17953fce38d562d7f01d583121745844295e221) to pass tests)
* running tests on demo.ckan.org is a wild rodeo of time-outs and varying server load

**Comment by sckott** [comment]
thanks @florianm 

yeah, using demo doesn't seem ideal, but an improvement perhaps?

i'd be happy to setup an instance to use for testing but my previous attempts haven't succeeded

**Pull request merged**
